# Generated by Django 4.0.2 on 2022-02-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
